[package]
name = "rcrd"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.2.0"
gif = "0.11.4"
image = "0.24.2"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
structopt = "0.3.26"
